name: Automatic workflow

on: [push, pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Greetings
      run: |
        echo "Hello World!"
        echo "Hello REF: $GITHUB_REF"
        echo "Hello HEAD_REF: $GITHUB_HEAD_REF"
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
