name: Automatic workflow

on: [push, pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Greetings
      run: |
        echo "Hello World!"
        echo "Hello REF: $GITHUB_REF"
        echo "Hello HEAD_REF: $GITHUB_HEAD_REF"
      
  deploy:
    name: Invoke deployment
    runs-on: ubuntu-latest
    needs: greeting
    if: contains(github.ref, 'refs/heads/development') || contains(github.ref, 'refs/heads/master')
    steps:
      - name: Invoke deployment workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual workflow
          token: ${{ secrets.PERSONAL_TOKEN }}
          
