name: Workflow run

on:
  workflow_run:
    workflows:
      - Manual workflow
    branches:
      - master
      - development
    types:
      - completed
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2.3.2

      - uses: nimblehq/branch-tag-action@v1.1
      
      - name: Print
        run: |
          echo ${{ github.ref }}
          echo "WORKFLOW_RUN:"
          echo ${{ github.event.workflow_run }}
          echo "WORKFLOW_RUN JSON:"
          echo ${{ toJSON(github.event.workflow_run) }}
          echo "GITHUB"
          echo ${{ toJSON(github) }}
