name: Workflow run

on:
  workflow_run:
    workflows:
      - Manual workflow
      - Automatic workflow
    types:
      - completed
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2.3.2
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - uses: nimblehq/branch-tag-action@v1.1
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}
      
      - name: Print
        run: |
          echo ${{ github.ref }}
          echo "BRANCH_TAG:"
          echo ${{ env.BRANCH_TAG }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
